#!/usr/bin/env bash
set -e
echo "# File generated by generate-authors.sh. DO NOT EDIT." > AUTHORS
echo "# This file lists all contributeors to the repository." >> AUTHORS
echo "# See generate-authors.sh to make modifications." >> AUTHORS
echo >> AUTHORS
git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf >> AUTHORS
